image: maven:3.5.4-jdk-10,
        mongo:3.2-jessie
before_script:
- apt-get update -qq && apt-get install
stages:
- test
- build
- codecoverage
test:
  script: mvn test
build:
  script: mvn package
codecoverage:
  script: mvn clean test