image: maven:3.5.4-jdk-10
before_script:
- apt-get update -qq && apt-get install
stages:
- test
- build
- codecoverage
test:
  script: mvn test
build:
  script: mvn package
codecoverage:
  script:
  - "mvn test"
  - "mvn jacoco:report"
  - "mvn xml:transform"
  - "echo \"$(cat target/generated-resources/xml/xslt/target/site/jacoco/jacoco.xml)% covered\""
#codecoverage:
#  script:
#    - mvn clean test
#    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
#  coverage: '\d+.\d+ \% 'covered
