image: maven:3.5.4-jdk-10
before_script:
- apt-get update -qq && apt-get install
stages:
- test
- build
- codecoverage
test:
  script: mvn test
build:
  script: mvn package
codecoverage:
  script:
    - mvn clean test
    - cat target/site/jacoco/index.html
  coverage: '\d+.\d+ \% '
