image: maven:3.5.4-jdk-10
before_script:
- apt-get update -qq && apt-get install
stages:
- test
- build
- codecoverage
test:
  script: mvn test
build:
  script: mvn package
codecoverage:
  script:
  - "mvn clean test"
  - "mvn jacoco:report"
  - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/",instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' config-server/target/site/jacoco/jacoco.csv
  coverage: '/Code coverage: \d+\.\d+/'
  artifacts:
      paths:
      - target/site/jacoco/
#codecoverage:
#  script:
#    - mvn clean test
#    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
#  coverage: '\d+.\d+ \% 'covered
