version:  '2'
services:
#  zookeeper:
#    container_name: zookeeper
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    container_name: kafka
#    image: wurstmeister/kafka
#    ports:
#      - "9092"
#    depends_on:
#      - "zookeeper"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  eureka:
    image: eureka:v1
    build: eureka-registry/
    restart: always
    container_name: eureka-container
    network_mode: host
    ports:
      - 8091:8091
    expose:
      - 8091

  config-server:
    image: config-server:v1
    build: config-server/
    restart: always
    container_name: config-container
    network_mode: host
    depends_on:
      - eureka
    ports:
      - 8092:8092
    expose:
      - 8092

 document-identifier:
    image: document-identifier:v1
    build: document-identifier/
    restart: always
    container_name: document-identifier
    network_mode: host
    depends_on:
    - kafka
    - mongodb
    ports:
    - "8080:8080"
    expose:
    - "8080" 
 mongodb:
    image: mongo:3.2-jessie
    ports:
      - "27017:27017"
    container_name: mongo-knowledgevault
    network_mode: host
    depends_on:
      - config-server
    volumes:
      - '/home/cgi/data/mysql:/data/db'

  mongo-demo:
    image: movie-mongo:v1
    build: movie-cruiser-app/
    restart: always
    container_name: mongo-demo-compose
    network_mode: host
    depends_on:
      - mongodb
    ports:
      - 8090:8090
    expose:
      - 8090

  gateway:
    image: zuulgateway:v1
    build: zuulgateway/
    restart: always
    container_name: zuul-container
    network_mode: host
    depends_on:
      - mongo-demo
    ports:
      - 8081:8081
    expose:
      - 8081
