version:  '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
    - "2181:2181"
    expose:
    - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: kafka
    ports:
    - "9092:9092"
    expose:
    - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.23.239.133
      KAFKA_CREATE_TOPICS: "education:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.23.239.133:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zookeeper
    restart: always

  document-identifier:
    image: document-identifier:v1
    build: document-identifier/
    restart: always
    container_name: "document-identifier"
    network_mode: host
    depends_on:
    - mongodb
    volumes:
    - '../knowledge-vault/document-identifier/:/knowledge-vault/document-identifier/'
    ports:
    - "8080:8080"
    expose:
    - "8080"

  mongodb:
    image: mongo:3.2-jessie
    ports:
    - 27017:27017
    container_name: "mongo-knowledgevault"
    network_mode: host
    volumes:
    - '../data/mongo:/data/db'
    environment:
      MONGO_INITDB_DATABASE: mydatabase

  extractor-service:
    image: extractor-service:v1
    build: extractor-service/
    restart: always
    container_name: "extractor-service"
    network_mode: host
    volumes:
    - '../knowledge-vault/extractor-service/src/main/resources/:/knowledge-vault/extractor-service/src/main/resources/'
    ports:
    - "8094:8094"
    expose:
    - "8094"

  paragraph-processor:
    image: paragraph-processor:v1
    build: paragraph-processor/
    restart: always
    container_name: "paragraph-processor"
    network_mode: host
    ports:
    - "8433:8433"
    expose:
    - "8433"

  paragraph-tokenizer:
    image: paragraph-tokenizer:v1
    build: paragraph-tokenizer/
    restart: always
    container_name: "paragraph-tokenizer"
    network_mode: host
    ports:
    - "8065:8065"
    expose:
    - "8065"

  populator:
    image: populator:v1
    build: populator/
    restart: always
    container_name: "populator"
    network_mode: host
    ports:
    - "8067:8067"
    expose:
    - "8067"